import Head from "next/head";
import styled from "styled-components";

export default function Contact() {
  const Hero = styled.div`
    height: 90vh;
    display: flex;
    justify-content: center;
    align-items: center;
    background: #fff;
  `;

  const Heading = styled.h1`
    color: #000;
    font-size: 10rem;
    font-weight: 900;
    @media (max-width: 768px) {
      font-size: 3rem;
      font-weight: 900;
    }
  `;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        <Heading>CONTACT</Heading>
      </Hero>
    </>
  );
}
